"""Fix fields User

Revision ID: 715358012ff4
Revises: a60d7b2866a1
Create Date: 2023-07-27 01:04:18.344527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715358012ff4'
down_revision = 'a60d7b2866a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
