"""Add User

Revision ID: 25802267c288
Revises: a520095fcbe6
Create Date: 2023-07-25 01:02:50.986593

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '25802267c288'
down_revision = 'a520095fcbe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('middle_name', sa.String(), nullable=True),
                    sa.Column('is_active', sa.String(), nullable=False),
                    sa.Column('is_verified', sa.String(), nullable=False),
                    sa.Column('is_superuser', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
